name: CI
on: [push, pull_request]
jobs:
  test-pg:
    runs-on: ubuntu-18.04

    services:
      pg:
        image: postgres:${{ matrix.pg_version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container: elixir:1.9-slim

    strategy:
      matrix:
        pg_version: ["9.5"]

    steps:
      - name: Install PG Client
        run: |
          apt-get update
          apt-get install -y wget ca-certificates gnupg
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main ${{ matrix.pg_version }}" >> /etc/apt/sources.list.d/pgdg.list
          apt-get update
          apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-contrib-${{ matrix.pg_version }}
          echo hello world1
          psql --version
          pg_dump --version
          PGPASSWORD=postgres psql -h pg -U postgres -d postgres -c 'SELECT version();'
          echo hello world2

      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          apt-get install -y git
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: PG_URL=postgres:postgres@pg ECTO_ADAPTER=pg mix test
